image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

Build:
  stage: build
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - yarn run build

Test:
  stage: test
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
  # Runs the tests.
    - yarn test

include:
  template: Dependency-Scanning.gitlab-ci.yml

