image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

Build:
  stage: build
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
    - npm run build

Test:
  stage: test
  before_script: 
    - yarn config set cache-folder .yarn
    - yarn install 
  script:
  # Installs Chrome
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub |  apt-key add -
    - echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' |  tee /etc/apt/sources.list.d/google-chrome.list
    - apt-get update 
    - apt-get install google-chrome-stable -y
  # Runs the tests.
    - npm run test:karma-headless

include:
  template: Dependency-Scanning.gitlab-ci.yml

